config/routes.rb
Greendrive::Application.routes.draw do  
  
  root :to => 'application#root'

  get 'gebruikers/:user_name/dashboard' => 'dashboards#index', :as => 'user_name_dashboard'
  get 'gebruikers/:user_name/badges' => 'badges#index', :as => 'user_name_badges'
  get 'leaderboards' => 'leaderboards#index', :as => 'user_name_leaderboard'
  get 'gebruikers/:user_name' => 'users#show', :as => 'user_name'
  get 'gebruikers/:user_name/bewerken' => 'users#edit', :as => 'user_name_edit'

  resources :pictures, :only => [:index, :create, :destroy]
  resources :authentications

  resources :password_resets
  
  match "/search_results/" => "application#search_results", :via => :get, :as =>"search_results"
  match "/empty" => "application#download"

  resources :cars

  resources :users do
    resources :segments
  end
  
  resources :users do 
    resources :badges
  end
  
  resources :users
  
  resources :users do
    resources :dashboards
  end

  resources :users do
    resources :cars
  end
  
  resources :cars do
    resources :segments 
  end
  
  resources :traces
  resources :pages

  resources :badges

  resources :leaderboards

  match 'faq' => 'pages#faq', :as => 'faq', :via => :get
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match 'homepage' => 'pages#homepage'
  
  match 'logout' => 'sessions#destroy', :as => 'logout'

  controller :sessions do
    get "login" => "sessions#new" 
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"
  end
  resources :sessions
  
   match "*path" => redirect("/") #Wrongly typed URL returns to root_path, keep it at the bottom of all the routes.
   

end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :provider, :rank, :terms_of_service, :image_cache, :uid, :role, :admin, :user, :email, :first_name, :middle_name, :last_name, :password_confirmation, :password, :user_name, :avatar, :birthday, :score

  has_secure_password 

  has_many :authentications
  has_many :traces
  has_one :car, :dependent => :destroy
  has_one :dashboard
  has_many :segments
  has_many :achievements
  has_many :badges, through: :achievements


  # validates_presence_of :password, :except => [:edit, :update] #Werkt niet grrr
  # validates_presence_of :password_confirmation, :except => [:edit, :update] #Werkt niet grrr
  # validates_format_of :password, :with => /(?=^.{6,20}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/


  validates_format_of :password, :with => /(?=^.{6,20}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/

  #Password: Length between 6-20 characters, which consists of [at least] 1 lowercase, 1 uppercase and 1 special character OR digit
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :user_name, :presence => true, :uniqueness => true, :length => {:minimum => 4,:maximum => 20}, :format => {:with => /[a-zA-Z0-9]$/}
  validates :email, :presence => true, :uniqueness => true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  validates_acceptance_of :terms_of_service, :on => :create# , :allow_nil => false
  
  before_create { generate_token(:auth_token) }
  mount_uploader :avatar, AvatarUploader

# def self.search(search)
#   if search
#     where('user_name || first_name || last_name LIKE ?' "%#{search}%", :format => {:with => /[\f]$/}) 
#   else
#     scoped
#   end
# end


# def self.search(search)
#   search_condition = "%" + search + "%"
#   find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition, search_condition])
# end



  # after_validation { self.errors.messages.delete(:password_digest) } 
  # ^ This way password_digest won't show up in the error explanation

  

  ##### /users/id wordt /users/username ####
  # extend FriendlyId
  # friendly_id :user_name

#### REMOVES WHITESPACE AND DASHES FROM LICENSE PLATE INPUT ####




  
####################


  # ------------------------------------
  # Forgot Password
  # ------------------------------------
  def generate_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!(validate: false) #This way password validation wont conflict
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  
  # ------------------------------------

  #used to add avatar to user profile
  


  # def self.from_omniauth(auth)
  #     where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
  #         if user.created_at.nil?
  #           user.created_at = Time.now
  #         end
  #         if user.oauth_token.nil?
  #           user.oauth_token = auth.credentials.token
  #         end
  #         if user.oauth_expires_at.nil?
  #           user.oauth_expires_at = Time.at(auth.credentials.expires_at)
  #         end       
  #       user.provider = auth.provider
  #       user.uid = auth.uid
  #       user.first_name = auth.info.first_name
  #       user.last_name = auth.info.last_name
  #       user.user_name = auth.info.name
  #       user.avatar = auth.info.image
  #       user.email = auth.extra.raw_info.email
  #     end
  # end


# #### FACEBOOK OMNIAUTH ####
#   def apply_omniauth(omniauth)
#     Rails.logger.info omniauth['info']['email']
#     self.email = omniauth['info']['email'] if email.blank?
#     authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
#   end
# ############################

  def password_required?
    (authentications.empty? || !password.blank?) && super
  end


#### ROLES USED WITH CANCAN ####
  ROLES = %w[admin user]
  def role_symbols
      [role.to_sym]
  end

  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r)}.sum
  end

  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero?}
  end

 ################################



end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :user_required, :except => [:new, :create]
  before_filter :get_user
  
  load_and_authorize_resource
  
  def index
    @users = User.search(params[:search])
  end

  def show
    get_car
  end
  
  def new
    @user = User.new
  end
    
  def create
    @user = User.new(params[:user])
    @user.role = 'user'
      if @user.save
        cookies[:auth_token] = @user.auth_token
        UserMailer.welcome_email(@user).deliver
        flash[:succes] = "Welkom " + @user.user_name + ". U ben succesvol ingelogd. Er is tevens een welkomst e-mail verstuurd naar uw e-mailadres."
        redirect_to new_car_path
      else
        flash[:alert] = "Niet alle velden zijn correct ingevuld."
        render :new
      end
  end
  
  def edit
    get_user
  end

  def update
    find_user
    respond_to do |format|
      if @user.update_attributes(params[:user])
       flash[:success] = 'Uw profiel is succesvol aangepast.'
       format.html { redirect_to user_name_path(current_user.user_name) }
      else
       flash[:alert] = 'Er is iets misgegaan. Mogelijk zijn niet alle velden correct ingevuld.'
       format.html { render :edit }
      end       
    end
  end 

  def destroy
    find_user
    # Used to remove connected files (avatar photos) from users
    # @user.remove_file
    # FileUtils.remove_dir("#{Rails.root}/public/uploads/user/avatar/#{@user.id}", :force => true)  
      
    # @user = User.find(params[:id])  
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end
end
 

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script>
function readURL(input) {
if (input.files && input.files[0]) {
var reader = new FileReader();

reader.onload = function (e) {
$('.avatar')
.attr('src', e.target.result);
};

reader.readAsDataURL(input.files[0]);
}
}
</script>

</head>


<div id="pagewrap">		
<%= form_for(@user) do |f| %>
	<div class="profile_border">
		<div class="wrapper grid2">	
			<article class="col">
				<div id="vertical-line-right">
					<ul>
						<li>
							<h2>Bewerken</h2>
						</li>
						<li>
							<% if @user.avatar? %>
							<%= image_tag @user.avatar_url(), :class => "avatar" %>
							<% else %>
							<%= image_tag("avatar.png", :alt => "default-avatar", :class => "avatar") %>
							<% end %>
						</li>
						<li>
						<%= f.file_field :avatar, :onchange => "javascript: readURL(this);"%>
						</li>
						<% if @user.new_record? %>
						<li>
			  			    <%= f.label :user_name, t('labels.user_name') %></strong><br />
			  			    <div class="tooltip"><%= f.text_field :user_name, :title => "De gebruikersnaam moet minimaal 4 en maximaal 20 tekens bevatten.", :class => 'field' %></div>
						</li>
						<% end %>
					
					</ul>
				</div>
			</article>
	
			<article class="col">
				<ul>
					<li class="left top">
					    <%= f.label :first_name, t('labels.first_name') %></strong><br>
					    <%= f.text_field :first_name, :class => 'field' %>
					</li>
					<li class="left">
	  				  	<%= f.label :middle_name, 'Tussenvoegsel' %><br />
	  				  	<%= f.text_field :middle_name, class: 'field' %>
	   				</li>

					<li class="left">
		  			    <%= f.label :last_name, 'Achternaam' %></strong><br>
		  			    <%= f.text_field :last_name, :class => 'field' %>
					</li>
					
						<li class="left">
	      <%= f.label :birthday, 'Geboortedatum' %><br />
	      <%= f.date_select("birthday", :start_year => Date.current.year - 18, 
	                                    :end_year => Date.current.year - 90,
	                                    :order => [:day, :month, :year],
	                                    :prompt => {:day => 'Dag', :month => 'Maand', :year => 'Jaar'},
	                                    :use_month_names => ['Januari', 'Februari', 'Maart', 'April', 'Mei', 'Juni', 'Juli', 'Augustus',
	                                    'September', 'Oktober', 'November', 'December']) %>
	    </li>
					<li class="left">
		  			    <%= f.label :email, 'E-mail'
		  			     %></strong><br />
		  			    <%= f.email_field :email, :class => 'field' %>
					</li>
					<li class="left">
					    <%= f.label :password, 'Wachtwoord' %></strong><br />
					   	<%= f.password_field :password, :class => 'field' %>
					    <div class='help_text' class='username_help_text'>
										<h2>Wachtwoord</h2>
                						<p>Uw wachtwoord bestaat uit:</p>
              							<p>- Minimaal 6 tekens</p>
                						<p>- Minimaal 1 hoofdletter en 1 kleine letter</p>
                						<p>- Minimaal 1 getal</p>
          							</div>
					</li>
					<li class="left">
					    <%= f.label :password_confirmation, 'Wachtwoord verificatie'%></strong><br />
					    <%= f.password_field :password_confirmation, :class => 'field' %>
					    <div class='help_text' class='username_help_text'>
										<h2>Wachtwoord</h2>
                						<p>Uw wachtwoord bestaat uit:</p>
              							<p>- Minimaal 6 tekens</p>
                						<p>- Minimaal 1 hoofdletter en 1 kleine letter</p>
                						<p>- Minimaal 1 getal</p>
          							</div>
					
					</li>
					
					<li class="left">
						<%= f.submit "Opslaan", :class => "button" %>
					</li>
				</ul>
			</article>
		</div>
	</div>
<% end %>
</div>

app/views/users/_user.html.erb
	  	<ul class="search_results">
	  		<li class="search_results_left">
					<% if user.avatar? %>
						<%= image_tag user.avatar_url(), :class => "avatar" %>
					<% else %>
						<%= image_tag("avatar.png", :alt => "default-avatar", :class => "avatar") %>
					<% end %>
			</li>
	  		<li class="search_results_middle">
	  			<p><strong><%= user.first_name %> <%= user.middle_name %> <%= user.last_name %></strong></p>
	  			<p><%= user.user_name %></p>
	  			<p>Kenteken: </p>
	  		</li>
	  		<li class="search_results_right">
	  			<p><%= link_to 'Dashboard bekijken', user_name_dashboard_path(user.user_name), :class => 'link' %></p>
	  		</li>
	  	</ul>

app/views/users/edit.html.erb
<% provide(:title, "Profiel bewerken")%>

<%= render 'form' %>

app/views/users/from_facebook.html.erb
<%= form_for(user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> zorgen ervoor dat deze gebruiker niet opgeslagen kan worden:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
 	  </ul>
    </div>
  <% end %>

 	 	<article class="col">
  				<div class="align-center">
  						<ul>
  							<li>
								<h2>Registreren</h2>
  							</li>
  							<li>
  							    <%= f.label :license_plate, t('labels.licence_plate')
  							     %></strong><br />
  							    <%= f.text_field :license_plate, :placeholder => '81TRR8', :class => 'field' %>
  							</li>
  							<li>
  							    <%= f.label :password, t('labels.password')
  							     %></strong><br />
  							    <%= f.password_field :password, :class => 'field' %>
  							</li>
  							<li>
  							    <%= f.label :password_confirmation, t('labels.password_confirmation')%></strong><br />
  							    <%= f.password_field :password_confirmation, :class => 'field' %>
								
							</li>
							
							<% if current_user %>
							<li><%= f.submit "Opslaan", class: 'button' %></li>
							<% end %>
  						
  						</ul>
  					</div>
  				</div>
  		</article>

  		<article class="col">
	<div class="align-center">
  					<div class="avatar_pre"></div>
					<ul>
  						<li>
  						<%= f.file_field :avatar%>

  					    <% if current_user %>
						<% else %>
						</li>
						<li><%= f.check_box :terms_of_service, class: 'checkbox' %>
						Ik ga akkoord met de voorwaarden *</li>
  			
						<li><%= f.check_box :terms_of_privacy, class: 'checkbox' %>
						Ik ga akkoord met de privacyverklaring *</li>
					
  					     <div><%= f.submit "Account aanmaken", :class => 'button' %></div>
  					    <% end %>
						</ul>
  				</div>
  			</div>
  		</article>
<% end %>

app/views/users/index.html.erb
<% if @users.any? %>
  <div id="users">
    <%= render @users %>
  </div>
  <% else %>
  Er zijn geen gebruikers gevonden met deze zoektermen.
  <% end %>



</div>

app/views/users/new.html.erb
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script>
function readURL(input) {
if (input.files && input.files[0]) {
var reader = new FileReader();

reader.onload = function (e) {
$('.avatar_pre')
.attr('src', e.target.result)
;
};

reader.readAsDataURL(input.files[0]);
}
}
</script>


</head>
<div id="pagewrap">
	<div class="wrapper grid3">
		<article class="col">
				<%= form_tag sessions_path do %>
				<ul>
					<li>
						<h2>Inloggen</h2>	
					</li>
					
					<li>
						<%= label :email, 'Email'%><br />
						<%= email_field_tag :email, params[:email], :class => 'field aligncenter', :placeholder => "E-mailadres" %><br />
					</li> 
					<li>	
						<%= label :password, 'Wachtwoord'%><br />
						<%= password_field_tag :password, '', :class => 'field', :placeholder => "Wachtwoord" %>
					</li>
					<li class="center">
						<p><%= link_to "Wachtwoord vergeten?", new_password_reset_path %></p>
					</li>
					<li class="center">
						<%= check_box_tag :remember_me, 1, params[:remember_me] %>
						<%= label_tag :remember_me, 'Onthoud mij' %>
					</li>
					<li class="center">
						<%= submit_tag 'Inloggen!', :class => "button" %>
					</li>
				</ul>
					
				<% end %>
				<!-- <div id="linkregister">
					<ul>
						<li>
							<%= link_to 'Nog geen account?', new_user_path %>
						</li>
					</ul>
				</div>	 -->		
					
		</article>
				
			<article class="col">
				<div id="register">
					<div class="aligncenter">
					
					<%= form_for(@user) do |f| %>
						<div id="vertical-line">
							
				
							<ul>
								<li>
									<h2>Registreren</h2>
								</li>
								<li>
								    <%= f.label :first_name, 'Voornaam *' %><br>
								    <%= f.text_field :first_name, :class => 'field' %>
								</li>
								<li>
									<%= f.label :middle_name, 'Tussenvoegsel' %><br>
									<%= f.text_field :middle_name, :class => 'field'%>
								<li>
					  			    <%= f.label :last_name, 'Achternaam *' %><br>
					  			    <%= f.text_field :last_name, :class => 'field' %>
								</li>
								<li>
					  			    <%= f.label :email, 'E-mail *' %><br />
					  			    <%= f.email_field :email, :class => 'field' %>
									</li>
								<li>
					  			    <%= f.label :user_name, 'Gebruikersnaam *' %><br />
									<%= f.text_field :user_name, :class => 'field' %>
									<div class='help_text' class='username_help_text'>
										<h2>Gebruikersnaam</h2>
										<p>Uw gebruikersnaam moet uniek zijn en moet minimaal 4 en maximaal 20 tekens bevatten.</p>
          							</div>
								</li>
								<li>
							      <%= f.label :birthday, 'Geboortedatum' %><br />
							      <%= f.date_select("birthday", :start_year => Date.current.year - 18, 
							                                    :end_year => Date.current.year - 90,
							                                    :order => [:day, :month, :year],
							                                    :prompt => {:day => 'Dag', :month => 'Maand', :year => 'Jaar'},
							                                    :use_month_names => ['Januari', 'Februari', 'Maart', 'April', 'Mei', 'Juni', 'Juli', 'Augustus',
							                                    'September', 'Oktober', 'November', 'December']) %>
						    </li>
								<li>
								    <%= f.label :password, 'Wachtwoord *' %><br />
								    <%= f.password_field :password, :title => "Het wachtwoord moet minimaal 6 karakters bevatten, waarvan 1 hoofdletter, 1 kleine letter en 1 getal.", :class => 'field' %>
								    <div class='help_text' class='username_help_text'>
										<h2>Wachtwoord</h2>
                						<p>Uw wachtwoord bestaat uit:</p>
              							<p>- Minimaal 6 tekens</p>
                						<p>- Minimaal 1 hoofdletter en 1 kleine letter</p>
                						<p>- Minimaal 1 getal</p>
          							</div>
								</li>
								<li>
								   <%= f.label :password_confirmation, 'Wachtwoord herhalen *' %><br />
								   <%= f.password_field :password_confirmation, :title => "Het wachtwoord moet minimaal 6 karakters bevatten, waarvan 1 hoofdletter, 1 kleine letter en 1 getal.", :class => 'field' %>
								   <div class='help_text' class='username_help_text'>
										<h2>Wachtwoord</h2>
                						<p>Uw wachtwoord bestaat uit:</p>
              							<p>- Minimaal 6 tekens</p>
                						<p>- Minimaal 1 hoofdletter en 1 kleine letter</p>
                						<p>- Minimaal 1 getal</p>
          							</div>
								</li>
							</ul>
							<p class="register_text">De met * gemarkeerde velden zijn verplicht.</p>
						</div>
					</div>
				</div>
			</article>
				
			<article class="col">
				<div id="register">	
					<div class="aligncenter">
						<ul>
							<li>
								<%= image_tag("avatar.png", :alt => "default-avatar", :class => "avatar_pre") %>
							</li>
							<li>
								<%= f.file_field :avatar, :onchange => "javascript: readURL(this);" %>
							</li>

							<li>
								<small><%= check_box :terms_of_service, 'true' %>

								Ik ga akkoord met de <!-- &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp -->	<a href="#" onclick="popup('terms_info')", class="link">voorwaarden</a> *

									<div id="blanket"></div> <!-- the black opacity screen around the popup -->

									<div id="terms_info">
										<a href="#" onclick="popup('terms_info')">Sluiten</a>
									</div>	
								</small>
							</li>
							<li class="center">	
						      	<%= f.submit "Account aanmaken", :class => 'button_register' %>
							</li>
						</ul>
						<% end %>
					</div>
					
				</div>
			</article>	
		</div>
</div>	
	 
	 
	 
	 
	 

app/views/users/new_facebook.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> zorgen ervoor dat deze gebruiker niet opgeslagen kan worden:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
 	  </ul>
    </div>
  <% end %>

 	 	<article class="col">
			<% if current_user %>
			<div class="edit">
			<% else %>
  			<div class="register">
			<% end %>
  				<div class="align-center">
  						<ul>
  							<li>
								<% if current_user %>
  								<h2>Bewerken</h2>
								<% else %>
								<h2>Registreren</h2>
								<% end %>
  							</li>
  							<li>
  							    <%= f.label :first_name, t('labels.first_name') %></strong><br>
  							    <%= f.text_field :first_name, :class => 'field' %>
  							</li>
  							<li>
  				  			    <%= f.label :last_name, t('labels.last_name') %></strong><br>
  				  			    <%= f.text_field :last_name, :class => 'field' %>
  							</li>
  							<li>
  				  			    <%= f.label :email, t('labels.email')
  				  			     %></strong><br />
  				  			    <%= f.text_field :email, :autofocus => true, :class => 'field' %>
  							</li>
  							<li>
  							    <%= f.label :license_plate, t('labels.licence_plate')
  							     %></strong><br />
  							    <%= f.text_field :license_plate, :placeholder => '81TRR8', :class => 'field' %>
  							</li>
  							<li>
  							    <%= f.label :password, t('labels.password')
  							     %></strong><br />
  							    <%= f.password_field :password, :class => 'field' %>
  							</li>
  							<li>
  							    <%= f.label :password_confirmation, t('labels.password_confirmation')%></strong><br />
  							    <%= f.password_field :password_confirmation, :class => 'field' %>
								
							</li>
							
							<% if current_user %>
							<li><%= f.submit "Opslaan", class: 'button' %></li>
							<% end %>
  						
  						</ul>
  					</div>
  				</div>
  		</article>

  		<article class="col">
			<% if current_user %>
			<div class="edit">
			<% else %>
  			<div class="register">
			<% end %>
  				<div class="align-center">
  					<div class="avatar_pre"></div>
					<ul>
  						<li>
  						<%= f.file_field :avatar%>

  					    <% if current_user %>
						<% else %>
						</li>
						<li><%= f.check_box :terms_of_service, class: 'checkbox' %>
						Ik ga akkoord met de voorwaarden *</li>
  			
						<li><%= f.check_box :terms_of_privacy, class: 'checkbox' %>
						Ik ga akkoord met de privacyverklaring *</li>
					
  					     <div><%= f.submit "Account aanmaken", :class => 'button' %></div>
  					    <% end %>
						</ul>
  				</div>
  			</div>
  		</article>
<% end %> 

app/views/users/show.html.erb
<% provide(:title, @user.user_name)%>
<div id="pagewrap">	
	<div class="profile_border">
		<div class="wrapper grid2">	
			<div class="col">
				<div id="vertical-line-right">
					<ul>
						<li>
							<h2>Profiel</h2>
						</li>
						<li>
							<% if @user.avatar? %>
								<%= image_tag @user.avatar_url(), :class => "avatar" %>
							<% else %>
								<%= image_tag("avatar.png", :alt => "default-avatar", :class => "avatar") %>
							<% end %>
						</li>
						<li class="center">
							<strong class="green">Gebruikersnaam</strong><br />
								<%= @user.user_name %>
						</li>
						<li class="center">
							<strong class="green">Model auto</strong><br /><%= @user.car.model %>
						</li>
						<li class="center">
							<strong class="green">Kenteken</strong><br /><%= @user.car.license_plate %>
						</li>
						<li class="center">
							<strong class="green">Deelname sinds</strong><br /><%= @user.created_at.strftime("%d %b. %Y") %>
						</li>
						
						<!-- <li class="center">
							<h3><%= link_to 'Badges', :class => "button" %></h3>
						</li> -->			
					</ul>
				</div>
					
			</div>

			<div class="col">
				<ul>
					<% if can? :update, @user %>
					<li class="right">
						<%= link_to 'Bewerken', user_name_edit_path(@user.user_name), :class => "button_small" %>
					</li>
					<% end %>
			
					<li class="left">
						<strong class="green">Naam</strong><br />
							<%= @user.first_name %> <%= @user.middle_name%> <%= @user.last_name %>
					</li>
					<li class="left">
						<strong class="green">E-mail</strong><br />
							<%= mail_to @user.email, @user.email %>
					</li>
					<li class="left">
					  	<strong class="green">Geboortedatum</strong><br />
					  		<% if @user.birthday.blank? %>
					  			<p>Er is geen geboortedatum ingevuld.</p>
					  		<% else %>
					    		<%= @user.birthday.strftime("%e-%-m-%Y")%>
					    	<% end %>
					</li>
						
				</ul>		
		</div>
	</div>
</div>