config/routes.rb
Greendrive::Application.routes.draw do  
  
  root :to => 'application#root'

  get 'gebruikers/:user_name/dashboard' => 'dashboards#index', :as => 'user_name_dashboard'
  get 'gebruikers/:user_name/badges' => 'badges#index', :as => 'user_name_badges'
  get 'leaderboards' => 'leaderboards#index', :as => 'user_name_leaderboard'
  get 'gebruikers/:user_name' => 'users#show', :as => 'user_name'
  get 'gebruikers/:user_name/bewerken' => 'users#edit', :as => 'user_name_edit'

  resources :pictures, :only => [:index, :create, :destroy]
  resources :authentications

  resources :password_resets
  
  match "/search_results/" => "application#search_results", :via => :get, :as =>"search_results"
  match "/empty" => "application#download"

  resources :cars

  resources :users do
    resources :segments
  end
  
  resources :users do 
    resources :badges
  end
  
  resources :users
  
  resources :users do
    resources :dashboards
  end

  resources :users do
    resources :cars
  end
  
  resources :cars do
    resources :segments 
  end
  
  resources :traces
  resources :pages

  resources :badges

  resources :leaderboards

  match 'faq' => 'pages#faq', :as => 'faq', :via => :get
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match 'homepage' => 'pages#homepage'
  
  match 'logout' => 'sessions#destroy', :as => 'logout'

  controller :sessions do
    get "login" => "sessions#new" 
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"
  end
  resources :sessions
  
   match "*path" => redirect("/") #Wrongly typed URL returns to root_path, keep it at the bottom of all the routes.
   

end

app/views/pages/faq.html.erb
<div id="pagewrap">
	<div class="wrapper fullwidth">
		<div id="container_faq">
			<h1>Veel gestelde vragen</h1>
			<p>Is iets niet duidelijk of wil je iets weten? Kijk eerst of het hier tussen staat en neem anders <%= link_to "contact", contact_url %> met ons op.</p>
			<ul id="accordion">
				<li>
					<h4>1. Wat is greendrivers?</h4>
						<p>Greendriver is een webapp waarin je o.a. badges en punten kunt halen, kunt competeren met collegas, vrienden en anderen. En je je eigen statistieken kunt bekijken en vergelijken.</p>
					<h4>2. Wat heb ik nodig om greendrivers te kunnen gebruiken?</h4>
						<p>Een compatibele auto(Opel Ampera) en een kastje om de data te verzamelen van Sycada.</p>
					<h4>3. Hoe kan ik de gegevens va mijn auto bekijken?</h4>
						<p>Door te registreren voor de applicatie en in te loggen met de gegevens van 360-ev.com kunnen wij de gegevens van de auto ophalen en weergeven in de applicatie.</p>
					<h4>4. Hoe kan ik zien hoeveel kilometers iemand anders heeft gereden?</h4>
						<p>Door een gebruiker te zoeken via de zoekbalk in de header kun je de gegevens van anderen bekijken.</p>
					<h4>5. Hoe kan ik mijn account verwijderen?</h4>	
						<p>Een account verwijderen kan op dit moment alleen door een mail te sturen. <small><%= link_to 'Ga naar contact', contact_path %></small>.</p>
					<h4>6. Hoeveel badges zijn er?</h4>
						<p>Op dit moment zijn er 5 actieve badges.</p>
					<h4>7. Hoe kan ik een badge halen?</h4>
						<p>Door te voldoen aan de kriteria voor de badge kan je deze behalen.</p>
					<h4>8. Waar kan ik zien welke badges ik al gehaald heb?</h4>
					<p>Op de pagina 'Badges' zijn alle behaalde en nog te behalen badges te zien.</p>
					<h4>9. Waar kan ik het verschil tussen elektriscche en fossiele kilometers zien?</h4>
					<p>Op het dashboard wordt in een diagram weergegeven hoeveel elektrische en hoeveel fossiele kilometers de auto heeft gereden.</p>
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/pages/homepage.html.erb
<div id="pagewrap">
	
	<div class="fullwidth">
		<%= link_to image_tag("logo_fullcolour.svg"), root_path, :class => 'logo' %>
	</div>
	
	<div class="col_home_side">
		<div id="block_1" data-explain_block="explain_1"></div>
		<div id="block_2" data-explain_block="explain_2"></div>
		<div id="block_3" data-explain_block="explain_3"></div>
		<div id="block_4" data-explain_block="explain_4"></div>
	</div>
	
	<div class="col_home_mid">
		<div id="container_explains">
			<div id="explain_0"><h1><strong class="green">"</strong>Welkom bij de wedstrijd <br /> voor meer <strong class="green">groene</strong> kilometers met uw <br />Plug In Hybride Voertuig<strong class="green">"</strong>
</h1></div>
			<div id="explain_1"><h1><strong class="green">"</strong>Maak een <strong class="green">wedstrijd</strong> van je idealen en ga voor jouw topprestatie<strong class="green">"</strong></h1></div>	
			<div id="explain_2"><h1><strong class="green">"</strong>Elektrisch rijden is stil, <br> <strong class="green">speel mee</strong> voor meer vogelgeluiden <br> in jouw leefomgeving<strong class="green">"</strong></h1></div>
			<div id="explain_3"><h1><strong class="green">"</strong>Balans in de <strong class="green">natuur</strong>, <br> evenveel CO2 in de atmosfeer als eruit<strong class="green">"</strong></h1></div>
			<div id="explain_4"><h1><strong class="green">"</strong>Wonen in gezonde lucht, <strong class="green">bouw mee</strong> aan een schone toekomst<strong class="green">"</strong></h1></div>
			<div id="explain_5"><h1><strong class="green">"</strong>Opslag van <strong class="green">elektriciteit</strong> is nog nooit zo gemakkelijk geweest<strong class="green">"</strong></h1></div>
			<div id="explain_6"><h1><strong class="green">"</strong>De schoonste <strong class="green">energie</strong> zit in je hoofd, gebruik die dan ook en denk na<strong class="green">"</strong></h1></div>
			<div id="explain_7"><h1><strong class="green">"</strong>Brandstof is zo verschrikkelijk fossiel, <br> je zou er mee op <strong class="green">moeten</strong> houden<strong class="green">"</strong></h1></div>
			<div id="explain_8"><h1><strong class="green">"</strong>Overal gemakkelijk afrekenen <br> met het <strong class="green">GreenFlux</strong> laadpasje<strong class="green">"</strong></h1></div>		
		</div>
		
		
		
		
		<iframe src="http://www.youtube.com/embed/5Z7LYd7i2b4" allowfullscreen></iframe>		
		<br>
		<br>
		<div id="container_button">
			<%= link_to "Inloggen", new_session_path, :class => "button_homepage" %>
			<%= link_to "Registreren", new_session_path, :class => "button_homepage" %>
		</div>
	</div>
		
	<div class="col_home_side">
		<div id="block_5" data-explain_block="explain_5"></div>
		<div id="block_6" data-explain_block="explain_6"></div>
		<div id="block_7" data-explain_block="explain_7"></div>
		<div id="block_8" data-explain_block="explain_8"></div>
	</div>