config/routes.rb
Greendrive::Application.routes.draw do  
  
  root :to => 'application#root'

  get 'gebruikers/:user_name/dashboard' => 'dashboards#index', :as => 'user_name_dashboard'
  get 'gebruikers/:user_name/badges' => 'badges#index', :as => 'user_name_badges'
  get 'leaderboards' => 'leaderboards#index', :as => 'user_name_leaderboard'
  get 'gebruikers/:user_name' => 'users#show', :as => 'user_name'
  get 'gebruikers/:user_name/bewerken' => 'users#edit', :as => 'user_name_edit'

  resources :pictures, :only => [:index, :create, :destroy]
  resources :authentications

  resources :password_resets
  
  match "/search_results/" => "application#search_results", :via => :get, :as =>"search_results"
  match "/empty" => "application#download"

  resources :cars

  resources :users do
    resources :segments
  end
  
  resources :users do 
    resources :badges
  end
  
  resources :users
  
  resources :users do
    resources :dashboards
  end

  resources :users do
    resources :cars
  end
  
  resources :cars do
    resources :segments 
  end
  
  resources :traces
  resources :pages

  resources :badges

  resources :leaderboards

  match 'faq' => 'pages#faq', :as => 'faq', :via => :get
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match 'homepage' => 'pages#homepage'
  
  match 'logout' => 'sessions#destroy', :as => 'logout'

  controller :sessions do
    get "login" => "sessions#new" 
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"
  end
  resources :sessions
  
   match "*path" => redirect("/") #Wrongly typed URL returns to root_path, keep it at the bottom of all the routes.
   

end

app/models/dashboard.rb
class Dashboard
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
 load_and_authorize_resource
 before_filter :get_user, :get_car

    
  def index

    begin
    @car_miles = { electric: @user.car.mileage_electric, fossile: @user.car.mileage_fossile }
    @car_miles_week = { electric: @user.car.last_week_electric, fossile: @user.car.last_week_fossile }
    @car_miles_month = { electric: @user.car.last_month_electric, fossile: @user.car.last_month_fossile }
    @car_miles_year = { electric: @user.car.last_year_electric, fossile: @user.car.last_year_fossile }
    

    rescue ActiveRecord::RecordNotFound
    	redirect_to root_path
    end
  end 
  # bundle exec whenever --update-crontab RAILS_ENV=production
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_charts.html.erb
<div id="all_date">

	<div id="chart_div1" data-car_miles='<%= @car_miles.to_json %>' style="width:500px; height:250px"></div>

	<ul class='chart_stats'>

		<li class=col_chart><p>Elektrisch</p> <%= @user.car.mileage_electric %> km </li>
		<li class=col_chart><p>Fossiel</p> <%= @user.car.mileage_fossile %> km </li>
		<li class=col_chart style='border:none'><p>Totaal</p> <%= @user.car.mileage %> km </li>

	</ul>
</div>

<div id="week_date">
	<div id="chart_div2" data-car_miles_week='<%= @car_miles_week.to_json %>' style="width:500px; height:250px"></div>

	<ul class='chart_stats'>

		<li class=col_chart><p>Elektrisch</p> <%= @user.car.last_week_electric %> km </li>
		<li class=col_chart><p>Fossiel</p> <%= @user.car.last_week_fossile %> km </li>
		<li class=col_chart style='border:none'><p>Totaal</p> <%= @user.car.last_week %> km </li>

	</ul>
</div>


<div id="month_date">
	<div id="chart_div3" data-car_miles_month='<%= @car_miles_month.to_json %>' style="width:500px; height:250px"></div>
	<ul class='chart_stats'>

		<li class=col_chart><p>Elektrisch</p> <%= @user.car.last_month_electric %> km </li>
		<li class=col_chart><p>Fossiel</p> <%= @user.car.last_month_fossile %> km </li>
		<li class=col_chart style='border:none'><p>Totaal</p> <%= @user.car.last_month %> km </li>

	</ul>
</div>

<div id="year_date">
	<div id="chart_div4" data-car_miles_year='<%= @car_miles_year.to_json %>' style="width:500px; height:250px"></div>
	<ul class='chart_stats'>

		<li class=col_chart><p>Elektrisch</p> <%= @user.car.last_year_electric %> km </li>
		<li class=col_chart><p>Fossiel</p> <%= @user.car.last_year_fossile %> km </li>
		<li class=col_chart style='border:none'><p>Totaal</p> <%= @user.car.last_year %> km </li>

	</ul>
</div>

app/views/dashboards/index.html.erb
<% provide(:title, "Dashboard")%>

<div id="pagewrap">
	<div id="blanket"></div>	

		<div id="col_dashboard_left">
			<div id='chart'>
				<ul class='chart_info'>
					<li class='nav_interval'><a href="#" id="week">Vorige week</a></li> |
					<li class='nav_interval'><a href="#" id="month">Vorige maand</a></li> |
					<li class='nav_interval'><a href="#" id="year">Vorig jaar</a></li> |
					<li class='nav_interval'><a href="#" id="all">Alles</a></li>
				</ul>
				<div id="legenda">
					<div id="licht">Elektrisch</div><br>
					<div id="donker">Fossiel</div> 
				</div>
				<%= render 'charts'%>
			</div>
						
			<ul id="badges" class="center">	


					<%= raw @user.badges.most_recent.map {|badge| image_tag badge.avatar_url(), :class => "badge_display" }.to_sentence %>

				
		
				
			</ul>	

		</div>
		<div id="col_dashboard_right">
			<div id="profile">
				<ul>
					<li class="center">
						<% if @user.avatar? %> 
						<%= image_tag @user.avatar_url(), :class => "avatar" %>
						<% else %>
						<%= image_tag("avatar.png", :alt => "default-avatar", :class => "avatar") %>
						<% end %>
					</li>
	
					<li class="center"><%= link_to @user.user_name, user_path(@user) %></li>
		
					<li class="center"><%= @user.first_name %> <%= @user.middle_name%> <%= @user.last_name %></li>
	
					<li class="center"><%= @user.car.model %></li>
	
				</ul>
			</div>
			<div class="nav_dashboard">
				<ul>
					<li class="center"><%= link_to 'Bekijk badges', user_name_badges_path(@user.user_name) %></li>
					<li class="center"><%= link_to 'Bekijk profiel', user_name_path(@user.user_name)%></li>
					<% if can? :destroy, :session %>
						<li class="center" style="background:none"><%= link_to 'Uitloggen', logout_path, method: :destroy %></li>
					<% end %>
				</ul>	
			</div>
		</div>
		<div id="tutorial">
			<div id="tutorial_1" class="arrow_box_bottom">
				<h1>Welkom bij Greendrivers</h1>
				<p>Om snel van start te kunnen gaan volgt hier een kleine uitleg over de applicatie</p>
				<a href="#" class="next">Volgende</a>
			</div>
			<div id="tutorial_2" class="arrow_box_right">
				<h1>Dit ben jij</h1>
				<div class="buttons">
					<a href="#" class="prev">Vorige</a>
					<a href="#" class="next">Volgende</a>	
				</div>
			</div>
			<div id="tutorial_3" class="arrow_box_left">
				<h1>Dit gaat over je auto</h1>
				<p>De kilometers van de afgelopen tijd kun je hier terug vinden.</p>
				<div class="buttons">
					<a href="#" class="prev">Vorige</a>
					<a href="#" class="next">Volgende</a>	
				</div>
			</div>
			<div id="tutorial_4" class="arrow_box_bottom">
				<h1>Dit zijn badges</h1>
				<p>Als beloning voor je rijgedrag verdien je badges, de laatste drie die je verdiend hebt vind je hier terug.</p>
			</div>
			<div id="tutorial_5" class="arrow_box_bottom">
				<h1>Dit zijn snelkoppelingen</h1>
				<p>Om snel door de applicatie te surfen.</p>
			</div>
			<div id="tutorial_6">
				<div class="arrow_box_top">Zoeken</div>
				<div class="arrow_box_top">Menu</div>
				<div class="arrow_box_top">Help</div>
				<div id="buttons_end">
					<a href="#" class="prev">Vorige</a>
					<a href="#" class="next">Afsluiten</a>

				</div>
			</div>
		</div>

</div>