config/routes.rb
Greendrive::Application.routes.draw do  
  
  root :to => 'application#root'

  get 'gebruikers/:user_name/dashboard' => 'dashboards#index', :as => 'user_name_dashboard'
  get 'gebruikers/:user_name/badges' => 'badges#index', :as => 'user_name_badges'
  get 'leaderboards' => 'leaderboards#index', :as => 'user_name_leaderboard'
  get 'gebruikers/:user_name' => 'users#show', :as => 'user_name'
  get 'gebruikers/:user_name/bewerken' => 'users#edit', :as => 'user_name_edit'

  resources :pictures, :only => [:index, :create, :destroy]
  resources :authentications

  resources :password_resets
  
  match "/search_results/" => "application#search_results", :via => :get, :as =>"search_results"
  match "/empty" => "application#download"

  resources :cars

  resources :users do
    resources :segments
  end
  
  resources :users do 
    resources :badges
  end
  
  resources :users
  
  resources :users do
    resources :dashboards
  end

  resources :users do
    resources :cars
  end
  
  resources :cars do
    resources :segments 
  end
  
  resources :traces
  resources :pages

  resources :badges

  resources :leaderboards

  match 'faq' => 'pages#faq', :as => 'faq', :via => :get
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match 'homepage' => 'pages#homepage'
  
  match 'logout' => 'sessions#destroy', :as => 'logout'

  controller :sessions do
    get "login" => "sessions#new" 
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"
  end
  resources :sessions
  
   match "*path" => redirect("/") #Wrongly typed URL returns to root_path, keep it at the bottom of all the routes.
   

end

app/views/layouts/_header.html.erb
<% unless controller.action_name == "homepage" %>
	<div class="header">
		<% if controller_name == "sessions"  || controller_name == "password_resets" %>
			<div id="pagewrap">
				<ul class="nav">
					<li class="home">
						<%= link_to image_tag("header_logo_white.svg"), root_path %>
					</li>
				</ul>
			</div>
		<% else %>
		<div id="pagewrap">
			<ul class="nav">
				<li class="home">
					<%= link_to image_tag("header_logo_white.svg"), root_path, :class => "logo_effect"%>
				</li>	
				<li class="icons_header" id="help_header">
					<%= image_tag("help.svg")%>
					<ul>
						<% if current_user %>
						<li><%= link_to 'Tutorial', user_name_dashboard_path(current_user.user_name, show_tutorial: true), id: 'help' %></li>					<li><%= link_to 'FAQ', faq_path %></li>
						<li><%= link_to 'Contact', contact_path %></li>
						<% else %>
						<li><%= link_to 'FAQ', faq_path %></li>
						<li><%= link_to 'Contact', contact_path %></li>
						<% end %>
					</ul>
				</li>
				<% if current_user %>		
				<li class="icons_header">
					<%= image_tag("menu.png", :alt => "menu") %>
						<ul>
							<li><%= link_to "Dashboard", root_path %></li>
							
							<li><%= link_to "Badges", user_name_badges_path(current_user.user_name) %></li>
							
				 		   	<li><%= link_to "Mijn profiel", user_name_path(current_user.user_name) %></li>

				   		    <li><%= link_to "Leaderboards", leaderboards_path %></li>
				   		    <% if can? :destroy, :session %>
				    	    	<li><%= link_to "Uitloggen", logout_path, :method => :destroy %></li>
				    	    <% end %>			
				  	  </ul>
				</li>
				<li class="icons_header">
					<%= form_tag ("/search_results"), :method => "get", :class=>"navbar-form" do %>
        				<%= text_field_tag ("search"), params[:search], :class => 'search-input span2', :placeholder => 'Zoek naar gebruikers...' %>&nbsp
       					<%= image_submit_tag("search.png") %>
    				<% end %>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %>
	</div>
<% end %>

		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
<title><%= full_title(yield(:title)) %></title>

<meta name="viewport" content="width=device-width; initial-scale=1.0">
<link rel="shortcut icon" href="/images/favicon.png">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag 'application', :media => "all" %>
</head>

<% if params[:first_visit] || params[:show_tutorial] %>
<body id="first_visit">
<% else %>
<body>
<% end  %>
			
		<%= render "layouts/header" %>
		
<div id="pagewrap">
	<div id="error_bar">
		<% if flash[:notice] %>
	    	<p class="notice"><%= flash[:notice] %></p>
	    <% end %>	 

	    <% if flash[:alert] %>
	   		<p class="alert"><%= flash[:alert] %></p>
	    <% end %>	 

	    <% if flash[:success] %>
	    	<p class="success"><%= flash[:success] %></p>
		<% end %>	
	</div>
</div>	
		
		<%= yield %>


<div id="footer">
	<p>
		Copyright &copy; 2013 Greendrivers |<%= link_to " Algemene Voorwaarden ", :controller => 'application', :action => 'download' %>
		|<%= link_to ' Contact ', contact_path %>
		|<%= link_to ' FAQ ', faq_path %>
	</p>
</div>
</body>
</html>